import { ALL_JOB_CATEGORIES } from './jobCategories';

export interface CategoryInfo {
  id: string;
  key: string;
  label: string;
}

export const CATEGORY_TO_KEY_ID_MAP: Record<string, CategoryInfo> = {
  'Électricien bâtiment': { id: '1', key: 'electricite', label: 'Électricien bâtiment' },
  'Électricien industriel': { id: '1', key: 'electricite', label: 'Électricien industriel' },
  'Électricien auto': { id: '1', key: 'electricite', label: 'Électricien auto' },
  'Plombier': { id: '2', key: 'plomberie', label: 'Plombier' },
  'Chauffagiste': { id: '2', key: 'plomberie', label: 'Chauffagiste' },
  'Maçon': { id: '3', key: 'maconnerie', label: 'Maçon' },
  'Maçon en banco / terre': { id: '3', key: 'maconnerie', label: 'Maçon en banco / terre' },
  'Menuisier bois': { id: '4', key: 'menuiserie', label: 'Menuisier bois' },
  'Menuisier aluminium': { id: '4', key: 'menuiserie', label: 'Menuisier aluminium' },
  'Menuisier métallique': { id: '4', key: 'menuiserie', label: 'Menuisier métallique' },
  'Menuisier fabricant meubles': { id: '4', key: 'menuiserie', label: 'Menuisier fabricant meubles' },
  'Ébéniste': { id: '4', key: 'menuiserie', label: 'Ébéniste' },
  'Tourneur sur bois': { id: '4', key: 'menuiserie', label: 'Tourneur sur bois' },
  'Sculpteur sur bois': { id: '4', key: 'menuiserie', label: 'Sculpteur sur bois' },
  'Peintre en bâtiment': { id: '5', key: 'peinture', label: 'Peintre en bâtiment' },
  'Peintre décorateur': { id: '5', key: 'peinture', label: 'Peintre décorateur' },
  'Peintre automobile': { id: '5', key: 'peinture', label: 'Peintre automobile' },
  'Peintre artistique': { id: '5', key: 'peinture', label: 'Peintre artistique' },
  'Carreleur': { id: '6', key: 'carrelage', label: 'Carreleur' },
  'Faïencier': { id: '6', key: 'carrelage', label: 'Faïencier' },
  'Marbrier': { id: '6', key: 'carrelage', label: 'Marbrier' },
  'Couvreur': { id: '7', key: 'couverture', label: 'Couvreur' },
  'Charpentier': { id: '7', key: 'couverture', label: 'Charpentier' },
  'Serrurier': { id: '8', key: 'serrurerie', label: 'Serrurier' },
  'Serrurier dépannage': { id: '8', key: 'serrurerie', label: 'Serrurier dépannage' },
  'Forgeron': { id: '8', key: 'serrurerie', label: 'Forgeron' },
  'Ferronnier': { id: '8', key: 'serrurerie', label: 'Ferronnier' },
  'Chaudronnier': { id: '8', key: 'serrurerie', label: 'Chaudronnier' },
  'Fabricant de portails': { id: '8', key: 'serrurerie', label: 'Fabricant de portails' },
  "Fabricant d'outils": { id: '8', key: 'serrurerie', label: "Fabricant d'outils" },
  'Soudeur': { id: '8', key: 'serrurerie', label: 'Soudeur' },
  'Plâtrier': { id: '9', key: 'platrerie', label: 'Plâtrier' },
  'Plaquiste': { id: '9', key: 'platrerie', label: 'Plaquiste' },
  'Poseur de faux plafonds': { id: '9', key: 'platrerie', label: 'Poseur de faux plafonds' },
  'Vitrier / Miroitier': { id: '10', key: 'vitrerie', label: 'Vitrier / Miroitier' },
  'Étancheur': { id: '11', key: 'etancheite', label: 'Étancheur' },
  'Façadier': { id: '11', key: 'etancheite', label: 'Façadier' },
  'Réparateur téléphone': { id: '12', key: 'reparation', label: 'Réparateur téléphone' },
  'Réparateur informatique': { id: '12', key: 'reparation', label: 'Réparateur informatique' },
  'Réparateur TV': { id: '12', key: 'reparation', label: 'Réparateur TV' },
  'Réparateur électroménager': { id: '12', key: 'reparation', label: 'Réparateur électroménager' },
  'Réparateur climatiseur': { id: '12', key: 'reparation', label: 'Réparateur climatiseur' },
  'Réparateur groupe électrogène': { id: '12', key: 'reparation', label: 'Réparateur groupe électrogène' },
  'Réparateur machines industrielles': { id: '12', key: 'reparation', label: 'Réparateur machines industrielles' },
  'Réparateur moteurs': { id: '12', key: 'reparation', label: 'Réparateur moteurs' },
  'Installateur panneaux solaires': { id: '13', key: 'energie', label: 'Installateur panneaux solaires' },
  'Installateur systèmes de pompage': { id: '13', key: 'energie', label: 'Installateur systèmes de pompage' },
  'Technicien fibre / internet': { id: '14', key: 'telecom', label: 'Technicien fibre / internet' },
  'Installateur antennes': { id: '14', key: 'telecom', label: 'Installateur antennes' },
  'Installateur caméras CCTV': { id: '14', key: 'telecom', label: 'Installateur caméras CCTV' },
  'Mécanicien automobile': { id: '15', key: 'mecanique', label: 'Mécanicien automobile' },
  'Mécanicien moto': { id: '15', key: 'mecanique', label: 'Mécanicien moto' },
  'Mécanicien tricycle': { id: '15', key: 'mecanique', label: 'Mécanicien tricycle' },
  'Mécanicien vélo': { id: '15', key: 'mecanique', label: 'Mécanicien vélo' },
  'Vulcanisateur': { id: '15', key: 'mecanique', label: 'Vulcanisateur' },
  'Carrossier': { id: '15', key: 'mecanique', label: 'Carrossier' },
  'Couturier': { id: '16', key: 'couture', label: 'Couturier' },
  'Styliste': { id: '16', key: 'couture', label: 'Styliste' },
  'Tailleur traditionnel': { id: '16', key: 'couture', label: 'Tailleur traditionnel' },
  'Brodeur': { id: '16', key: 'couture', label: 'Brodeur' },
  'Tisserand': { id: '16', key: 'couture', label: 'Tisserand' },
  'Cordonnier': { id: '17', key: 'cuir', label: 'Cordonnier' },
  'Maroquinier': { id: '17', key: 'cuir', label: 'Maroquinier' },
  'Fabricant chaussures': { id: '17', key: 'cuir', label: 'Fabricant chaussures' },
  'Fabricant sacs': { id: '17', key: 'cuir', label: 'Fabricant sacs' },
  'Coiffeur': { id: '18', key: 'beaute', label: 'Coiffeur' },
  'Coiffeur dame': { id: '18', key: 'beaute', label: 'Coiffeur dame' },
  'Coiffeur homme / barbier': { id: '18', key: 'beaute', label: 'Coiffeur homme / barbier' },
  'Esthéticienne': { id: '18', key: 'beaute', label: 'Esthéticienne' },
  'Maquilleur': { id: '18', key: 'beaute', label: 'Maquilleur' },
  'Fabricant savon': { id: '19', key: 'cosmetique', label: 'Fabricant savon' },
  'Fabricant cosmétiques naturels': { id: '19', key: 'cosmetique', label: 'Fabricant cosmétiques naturels' },
  'Fabricant beurre de karité': { id: '19', key: 'cosmetique', label: 'Fabricant beurre de karité' },
  'Fabricant huiles naturelles': { id: '19', key: 'cosmetique', label: 'Fabricant huiles naturelles' },
  'Boulanger': { id: '20', key: 'alimentation', label: 'Boulanger' },
  'Pâtissier': { id: '20', key: 'alimentation', label: 'Pâtissier' },
  'Traiteur': { id: '20', key: 'alimentation', label: 'Traiteur' },
  'Restaurateur artisanal': { id: '20', key: 'alimentation', label: 'Restaurateur artisanal' },
  'Boucher': { id: '20', key: 'alimentation', label: 'Boucher' },
  'Charcutier': { id: '20', key: 'alimentation', label: 'Charcutier' },
  'Poissonnier': { id: '20', key: 'alimentation', label: 'Poissonnier' },
  'Fromager': { id: '20', key: 'alimentation', label: 'Fromager' },
  'Brasseur artisanal': { id: '20', key: 'alimentation', label: 'Brasseur artisanal' },
  'Fabricant jus naturels': { id: '20', key: 'alimentation', label: 'Fabricant jus naturels' },
  'Torréfacteur café': { id: '20', key: 'alimentation', label: 'Torréfacteur café' },
  'Sculpteur': { id: '21', key: 'art', label: 'Sculpteur' },
  'Céramiste': { id: '21', key: 'art', label: 'Céramiste' },
  'Potier': { id: '21', key: 'art', label: 'Potier' },
  'Fabricant bijoux': { id: '21', key: 'art', label: 'Fabricant bijoux' },
  'Bijoutier': { id: '21', key: 'art', label: 'Bijoutier' },
  'Orfèvre': { id: '21', key: 'art', label: 'Orfèvre' },
  'Graveur': { id: '21', key: 'art', label: 'Graveur' },
  'Fabricant objets décoratifs': { id: '21', key: 'art', label: 'Fabricant objets décoratifs' },
  'Vannier': { id: '22', key: 'artisanat', label: 'Vannier' },
  'Fabricant paniers': { id: '22', key: 'artisanat', label: 'Fabricant paniers' },
  'Fabricant nattes': { id: '22', key: 'artisanat', label: 'Fabricant nattes' },
  'Fabricant balais': { id: '22', key: 'artisanat', label: 'Fabricant balais' },
  'Fabricant calebasses': { id: '22', key: 'artisanat', label: 'Fabricant calebasses' },
  'Fabricant masques': { id: '22', key: 'artisanat', label: 'Fabricant masques' },
  'Fabricant instruments traditionnels': { id: '22', key: 'artisanat', label: 'Fabricant instruments traditionnels' },
  'Fabricant statues': { id: '22', key: 'artisanat', label: 'Fabricant statues' },
  'Apiculteur': { id: '23', key: 'environnement', label: 'Apiculteur' },
  'Fabricant miel': { id: '23', key: 'environnement', label: 'Fabricant miel' },
  'Fabricant charbon écologique': { id: '23', key: 'environnement', label: 'Fabricant charbon écologique' },
  'Fabricant briquettes combustibles': { id: '23', key: 'environnement', label: 'Fabricant briquettes combustibles' },
  'Recycleur artisanal': { id: '23', key: 'environnement', label: 'Recycleur artisanal' },
  'Fabricant compost': { id: '23', key: 'environnement', label: 'Fabricant compost' },
  'Chauffeur': { id: '24', key: 'transport', label: 'Chauffeur' },
  'Livreur': { id: '24', key: 'transport', label: 'Livreur' },
  'Déménageur artisanal': { id: '25', key: 'services', label: 'Déménageur artisanal' },
  'Nettoyage professionnel': { id: '25', key: 'services', label: 'Nettoyage professionnel' },
  'Aide ménagère': { id: '25', key: 'services', label: 'Aide ménagère' },
  'Agent de sécurité': { id: '26', key: 'securite', label: 'Agent de sécurité' },
  'Garde du corps': { id: '26', key: 'securite', label: 'Garde du corps' },
  'Gardien': { id: '26', key: 'securite', label: 'Gardien' },
};

export function getCategoryInfo(label: string): CategoryInfo | undefined {
  return CATEGORY_TO_KEY_ID_MAP[label];
}

export const METIER_TO_CATEGORY_MAP: Record<string, string[]> = {
  'Électricien bâtiment': ['Électricien bâtiment'],
  'Électricien industriel': ['Électricien industriel'],
  'Électricien auto': ['Électricien auto'],
  'Plombier': ['Plombier'],
  'Maçon': ['Maçon'],
  'Maçon en banco / terre': ['Maçon en banco / terre'],
  'Menuisier bois': ['Menuisier bois'],
  'Menuisier aluminium': ['Menuisier aluminium'],
  'Menuisier métallique': ['Menuisier métallique'],
  'Menuisier fabricant meubles': ['Menuisier fabricant meubles'],
  'Peintre en bâtiment': ['Peintre en bâtiment'],
  'Peintre décorateur': ['Peintre décorateur'],
  'Peintre automobile': ['Peintre automobile'],
  'Peintre artistique': ['Peintre artistique'],
  'Carreleur': ['Carreleur'],
  'Faïencier': ['Faïencier'],
  'Couvreur': ['Couvreur'],
  'Chauffagiste': ['Chauffagiste'],
  'Soudeur': ['Soudeur'],
  'Mécanicien automobile': ['Mécanicien automobile'],
  'Mécanicien moto': ['Mécanicien moto'],
  'Mécanicien tricycle': ['Mécanicien tricycle'],
  'Mécanicien vélo': ['Mécanicien vélo'],
  'Couturier': ['Couturier'],
  'Styliste': ['Styliste'],
  'Tailleur traditionnel': ['Tailleur traditionnel'],
  'Vitrier / Miroitier': ['Vitrier / Miroitier'],
  'Charpentier': ['Charpentier'],
  'Ébéniste': ['Ébéniste'],
  'Serrurier': ['Serrurier'],
  'Serrurier dépannage': ['Serrurier dépannage'],
  'Forgeron': ['Forgeron'],
  'Ferronnier': ['Ferronnier'],
  'Chaudronnier': ['Chaudronnier'],
  'Plâtrier': ['Plâtrier'],
  'Plaquiste': ['Plaquiste'],
  'Marbrier': ['Marbrier'],
  'Étancheur': ['Étancheur'],
  'Façadier': ['Façadier'],
  'Poseur de faux plafonds': ['Poseur de faux plafonds'],
  'Réparateur téléphone': ['Réparateur téléphone'],
  'Réparateur informatique': ['Réparateur informatique'],
  'Réparateur TV': ['Réparateur TV'],
  'Réparateur électroménager': ['Réparateur électroménager'],
  'Réparateur climatiseur': ['Réparateur climatiseur'],
  'Réparateur groupe électrogène': ['Réparateur groupe électrogène'],
  'Réparateur machines industrielles': ['Réparateur machines industrielles'],
  'Réparateur moteurs': ['Réparateur moteurs'],
  'Installateur panneaux solaires': ['Installateur panneaux solaires'],
  'Installateur systèmes de pompage': ['Installateur systèmes de pompage'],
  'Technicien fibre / internet': ['Technicien fibre / internet'],
  'Installateur antennes': ['Installateur antennes'],
  'Installateur caméras CCTV': ['Installateur caméras CCTV'],
  'Vulcanisateur': ['Vulcanisateur'],
  'Carrossier': ['Carrossier'],
  'Tourneur sur bois': ['Tourneur sur bois'],
  'Sculpteur sur bois': ['Sculpteur sur bois'],
  'Sculpteur': ['Sculpteur'],
  'Brodeur': ['Brodeur'],
  'Tisserand': ['Tisserand'],
  'Cordonnier': ['Cordonnier'],
  'Maroquinier': ['Maroquinier'],
  'Fabricant chaussures': ['Fabricant chaussures'],
  'Fabricant sacs': ['Fabricant sacs'],
  'Fabricant de portails': ['Fabricant de portails'],
  'Fabricant d\'outils': ['Fabricant d\'outils'],
  'Coiffeur': ['Coiffeur'],
  'Coiffeur dame': ['Coiffeur dame'],
  'Coiffeur homme / barbier': ['Coiffeur homme / barbier'],
  'Esthéticienne': ['Esthéticienne'],
  'Maquilleur': ['Maquilleur'],
  'Fabricant savon': ['Fabricant savon'],
  'Fabricant cosmétiques naturels': ['Fabricant cosmétiques naturels'],
  'Fabricant beurre de karité': ['Fabricant beurre de karité'],
  'Fabricant huiles naturelles': ['Fabricant huiles naturelles'],
  'Boulanger': ['Boulanger'],
  'Pâtissier': ['Pâtissier'],
  'Traiteur': ['Traiteur'],
  'Restaurateur artisanal': ['Restaurateur artisanal'],
  'Boucher': ['Boucher'],
  'Charcutier': ['Charcutier'],
  'Poissonnier': ['Poissonnier'],
  'Fromager': ['Fromager'],
  'Brasseur artisanal': ['Brasseur artisanal'],
  'Fabricant jus naturels': ['Fabricant jus naturels'],
  'Torréfacteur café': ['Torréfacteur café'],
  'Céramiste': ['Céramiste'],
  'Potier': ['Potier'],
  'Fabricant bijoux': ['Fabricant bijoux'],
  'Bijoutier': ['Bijoutier'],
  'Orfèvre': ['Orfèvre'],
  'Graveur': ['Graveur'],
  'Fabricant objets décoratifs': ['Fabricant objets décoratifs'],
  'Vannier': ['Vannier'],
  'Fabricant paniers': ['Fabricant paniers'],
  'Fabricant nattes': ['Fabricant nattes'],
  'Fabricant balais': ['Fabricant balais'],
  'Fabricant calebasses': ['Fabricant calebasses'],
  'Fabricant masques': ['Fabricant masques'],
  'Fabricant instruments traditionnels': ['Fabricant instruments traditionnels'],
  'Fabricant statues': ['Fabricant statues'],
  'Apiculteur': ['Apiculteur'],
  'Fabricant miel': ['Fabricant miel'],
  'Fabricant charbon écologique': ['Fabricant charbon écologique'],
  'Fabricant briquettes combustibles': ['Fabricant briquettes combustibles'],
  'Recycleur artisanal': ['Recycleur artisanal'],
  'Fabricant compost': ['Fabricant compost'],
  'Déménageur artisanal': ['Déménageur artisanal'],
  'Nettoyage professionnel': ['Nettoyage professionnel'],
  'Chauffeur': ['Chauffeur'],
  'Livreur': ['Livreur'],
  'Aide ménagère': ['Aide ménagère'],
  'Agent de sécurité': ['Agent de sécurité'],
  'Garde du corps': ['Garde du corps'],
  'Gardien': ['Gardien'],
};

export function getJobCategoriesForMetiers(metiers: string[]): string[] {
  if (!metiers || metiers.length === 0) {
    return [];
  }

  const categories = new Set<string>();

  metiers.forEach(metier => {
    const mappedCategories = METIER_TO_CATEGORY_MAP[metier];
    if (mappedCategories) {
      mappedCategories.forEach(cat => categories.add(cat));
    } else if (ALL_JOB_CATEGORIES.includes(metier)) {
      categories.add(metier);
    }
  });

  return Array.from(categories);
}
