import { ALL_JOB_CATEGORIES } from './jobCategories';

export const METIER_TO_CATEGORY_MAP: Record<string, string[]> = {
  'Électricien bâtiment': ['Électricien bâtiment'],
  'Électricien industriel': ['Électricien industriel'],
  'Électricien auto': ['Électricien auto'],
  'Plombier': ['Plombier'],
  'Maçon': ['Maçon'],
  'Maçon en banco / terre': ['Maçon en banco / terre'],
  'Menuisier bois': ['Menuisier bois'],
  'Menuisier aluminium': ['Menuisier aluminium'],
  'Menuisier métallique': ['Menuisier métallique'],
  'Menuisier fabricant meubles': ['Menuisier fabricant meubles'],
  'Peintre en bâtiment': ['Peintre en bâtiment'],
  'Peintre décorateur': ['Peintre décorateur'],
  'Peintre automobile': ['Peintre automobile'],
  'Peintre artistique': ['Peintre artistique'],
  'Carreleur': ['Carreleur'],
  'Faïencier': ['Faïencier'],
  'Couvreur': ['Couvreur'],
  'Chauffagiste': ['Chauffagiste'],
  'Soudeur': ['Soudeur'],
  'Mécanicien automobile': ['Mécanicien automobile'],
  'Mécanicien moto': ['Mécanicien moto'],
  'Mécanicien tricycle': ['Mécanicien tricycle'],
  'Mécanicien vélo': ['Mécanicien vélo'],
  'Couturier': ['Couturier'],
  'Styliste': ['Styliste'],
  'Tailleur traditionnel': ['Tailleur traditionnel'],
  'Vitrier / Miroitier': ['Vitrier / Miroitier'],
  'Charpentier': ['Charpentier'],
  'Ébéniste': ['Ébéniste'],
  'Serrurier': ['Serrurier'],
  'Serrurier dépannage': ['Serrurier dépannage'],
  'Forgeron': ['Forgeron'],
  'Ferronnier': ['Ferronnier'],
  'Chaudronnier': ['Chaudronnier'],
  'Plâtrier': ['Plâtrier'],
  'Plaquiste': ['Plaquiste'],
  'Marbrier': ['Marbrier'],
  'Étancheur': ['Étancheur'],
  'Façadier': ['Façadier'],
  'Poseur de faux plafonds': ['Poseur de faux plafonds'],
  'Réparateur téléphone': ['Réparateur téléphone'],
  'Réparateur informatique': ['Réparateur informatique'],
  'Réparateur TV': ['Réparateur TV'],
  'Réparateur électroménager': ['Réparateur électroménager'],
  'Réparateur climatiseur': ['Réparateur climatiseur'],
  'Réparateur groupe électrogène': ['Réparateur groupe électrogène'],
  'Réparateur machines industrielles': ['Réparateur machines industrielles'],
  'Réparateur moteurs': ['Réparateur moteurs'],
  'Installateur panneaux solaires': ['Installateur panneaux solaires'],
  'Installateur systèmes de pompage': ['Installateur systèmes de pompage'],
  'Technicien fibre / internet': ['Technicien fibre / internet'],
  'Installateur antennes': ['Installateur antennes'],
  'Installateur caméras CCTV': ['Installateur caméras CCTV'],
  'Vulcanisateur': ['Vulcanisateur'],
  'Carrossier': ['Carrossier'],
  'Tourneur sur bois': ['Tourneur sur bois'],
  'Sculpteur sur bois': ['Sculpteur sur bois'],
  'Sculpteur': ['Sculpteur'],
  'Brodeur': ['Brodeur'],
  'Tisserand': ['Tisserand'],
  'Cordonnier': ['Cordonnier'],
  'Maroquinier': ['Maroquinier'],
  'Fabricant chaussures': ['Fabricant chaussures'],
  'Fabricant sacs': ['Fabricant sacs'],
  'Fabricant de portails': ['Fabricant de portails'],
  'Fabricant d\'outils': ['Fabricant d\'outils'],
  'Coiffeur': ['Coiffeur'],
  'Coiffeur dame': ['Coiffeur dame'],
  'Coiffeur homme / barbier': ['Coiffeur homme / barbier'],
  'Esthéticienne': ['Esthéticienne'],
  'Maquilleur': ['Maquilleur'],
  'Fabricant savon': ['Fabricant savon'],
  'Fabricant cosmétiques naturels': ['Fabricant cosmétiques naturels'],
  'Fabricant beurre de karité': ['Fabricant beurre de karité'],
  'Fabricant huiles naturelles': ['Fabricant huiles naturelles'],
  'Boulanger': ['Boulanger'],
  'Pâtissier': ['Pâtissier'],
  'Traiteur': ['Traiteur'],
  'Restaurateur artisanal': ['Restaurateur artisanal'],
  'Boucher': ['Boucher'],
  'Charcutier': ['Charcutier'],
  'Poissonnier': ['Poissonnier'],
  'Fromager': ['Fromager'],
  'Brasseur artisanal': ['Brasseur artisanal'],
  'Fabricant jus naturels': ['Fabricant jus naturels'],
  'Torréfacteur café': ['Torréfacteur café'],
  'Céramiste': ['Céramiste'],
  'Potier': ['Potier'],
  'Fabricant bijoux': ['Fabricant bijoux'],
  'Bijoutier': ['Bijoutier'],
  'Orfèvre': ['Orfèvre'],
  'Graveur': ['Graveur'],
  'Fabricant objets décoratifs': ['Fabricant objets décoratifs'],
  'Vannier': ['Vannier'],
  'Fabricant paniers': ['Fabricant paniers'],
  'Fabricant nattes': ['Fabricant nattes'],
  'Fabricant balais': ['Fabricant balais'],
  'Fabricant calebasses': ['Fabricant calebasses'],
  'Fabricant masques': ['Fabricant masques'],
  'Fabricant instruments traditionnels': ['Fabricant instruments traditionnels'],
  'Fabricant statues': ['Fabricant statues'],
  'Apiculteur': ['Apiculteur'],
  'Fabricant miel': ['Fabricant miel'],
  'Fabricant charbon écologique': ['Fabricant charbon écologique'],
  'Fabricant briquettes combustibles': ['Fabricant briquettes combustibles'],
  'Recycleur artisanal': ['Recycleur artisanal'],
  'Fabricant compost': ['Fabricant compost'],
  'Déménageur artisanal': ['Déménageur artisanal'],
  'Nettoyage professionnel': ['Nettoyage professionnel'],
  'Chauffeur': ['Chauffeur'],
  'Livreur': ['Livreur'],
  'Aide ménagère': ['Aide ménagère'],
  'Agent de sécurité': ['Agent de sécurité'],
  'Garde du corps': ['Garde du corps'],
  'Gardien': ['Gardien'],
};

export function getJobCategoriesForMetiers(metiers: string[]): string[] {
  if (!metiers || metiers.length === 0) {
    return [];
  }

  const categories = new Set<string>();

  metiers.forEach(metier => {
    const mappedCategories = METIER_TO_CATEGORY_MAP[metier];
    if (mappedCategories) {
      mappedCategories.forEach(cat => categories.add(cat));
    } else if (ALL_JOB_CATEGORIES.includes(metier)) {
      categories.add(metier);
    }
  });

  return Array.from(categories);
}
